---
- name: Des lookups
  hosts: debiancli

  vars:
    site_toulouse: Ansible
    site_lyon: Kubernetes
    centres:
      - toulouse
      - lyon

  tasks:
    - name: Lookup DNS
      ansible.builtin.debug:
        msg: "kernel.org: {{ lookup('dig','kernel.org') }}"

    - name: Lookup env
      ansible.builtin.debug:
        msg: "PATH: {{ lookup('env','PATH') }}"

    - name: Lecture d'un fichier
      ansible.builtin.debug:
        msg: "{{ lookup('file','/tmp/hosts.txt') }}"

    - name: Lookup vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars','site_'+item) }}"
      loop: "{{ centres }}"
