---
- name: Création de groupes et comptes utilisateur
  hosts: all
  become: true

  tasks:
    - name: Chargement de la variable logins
      ansible.builtin.include_vars:
        file: logins.yml

    - name: Création des groupes
      ansible.builtin.group:
        name: "{{ item.1 }}"
      loop: "{{ logins | subelements('groupes') }}"

    - name: Création des comptes
      ansible.builtin.user:
        name: "{{ item.login }}"
        uid: "{{ item.uid }}"
        shell: "{{ item.shell }}"
        home: "{{ item.home }}"
        groups: "{{ item.groupes }}"
      loop: "{{ logins }}"
