---
- name: Chiffrement de mots de passe
  hosts: localhost

  tasks:
    - name: filtre password_hash
      ansible.builtin.debug:
        msg: "Password: {{ 'azerty' | password_hash('sha512','YBq939cc27bGruVA') }}"
