---
- name: Les boucles avec loop
  hosts: debiancli

  vars:
    stagiaires:
      - nom: Ahcene
        langages:
          - C
          - JS
      - nom: Olivier
        langages:
          - Bash
          - Python
      - nom: Lionel
        langages:
          - Assembleur
          - C
      - nom: Antoine
        langages:
          - Fortran
          - PHP
      - nom: Sébastien
        langages:
          - C
          - Assembleur68000
      - nom: Rémi
        langages:
          - Bash
          - Python
          - JS
      - nom: Christophe
        langages:
          - Ada
          - Powershell
      - nom: Éric
        langages:
          - PLSQL
          - PHP
      - nom: Bob

  tasks:
    - name: Affichage des valeur un deux et trois
      ansible.builtin.debug:
        msg: "Valeur n°{{ idx+1 }}: {{ rang }}"
      loop:
        - un
        - deux
        - trois
      loop_control:
        loop_var: rang
        index_var: idx 

    - name: Affichage des adresses IP de la cible
      ansible.builtin.debug:
        msg: "ip: {{ item }}"
      loop: "{{ ansible_all_ipv4_addresses }}"

    - name: Pour chaque stagiaire, itérer sur les langages annoncés
      ansible.builtin.debug:
        msg: "{{ item.0.nom }}: {{ item.1 }}"
      loop: "{{ stagiaires | subelements('langages',skip_missing=true) }}"
      tags: inloop
